@startuml

title Lexi: Full Design

allowmixing
left to right direction

note as general
    <b>Design Patterns</b>
    <i>Elements of Reusable Object-Oriented Software</i>
        <b>Lexi :</b>         Graphical document editor design
        <b>Scope: </b>     Document Structure, Formatting
        <b>Patterns:</b> Composite
end note

rectangle lexi.glyph.Glyph
rectangle lexi.glyph.GlyphComposite
rectangle lexi.glyph.GlyphLeaf
rectangle lexi.glyph.GlyphCharacter
rectangle lexi.glyph.GlyphRectangle
rectangle lexi.glyph.GlyphPolygon
rectangle lexi.glyph.GlyphRow
rectangle lexi.glyph.GlyphColumn

!includesub lexi_classes_structure.puml!RELATIONS

'-------------------------------------
' Formatting

rectangle lexi.strategy.GlyphStrategyCompositor
rectangle lexi.strategy.GlyphStrategyArrayCompositor
rectangle lexi.strategy.GlyphStrategyTeXCompositor
rectangle lexi.strategy.GlyphStrategySimpleCompositor


!includesub lexi_classes_format.puml!RELATIONS

'-------------------------------------------
' User interface imbellishment

rectangle lexi.decorator.GlyphDecorator
rectangle lexi.decorator.GlyphDecoratorBorder
rectangle lexi.decorator.GlyphDecoratorScroller

!includesub lexi_classes_imbellishment.puml!RELATIONS


@enduml