@startuml
salt

{+
    ' -----> Header
'    {
        {     [  L ] |
           "Lexi                                                                                  " | 
            [-] | 
            [O] | 
            [X] 
        }
'    }  
    ' <--- Header
    
    ' ------ > Body
    {
    }
    ' <------  Body

    {#
        {
            Header
        }
        {#
        .|.|
        {
            {Menu}
            {Body}
        }
        }
    }
    
}


@enduml