@startuml

title Lexi: Full Design

allowmixing
left to right direction

note as general
    <b>Design Patterns</b>
    <i>Elements of Reusable Object-Oriented Software</i>
        <b>Lexi :</b>         Graphical document editor design
        <b>Scope: </b>     Document Structure, Formatting
        <b>Patterns:</b> Composite
end note

package lexi.glyph {
    rectangle Glyph
    rectangle GlyphComposite
    rectangle GlyphLeaf
    rectangle GlyphCharacter
    rectangle GlyphRectangle
    rectangle GlyphPolygon
    rectangle GlyphRow
    rectangle GlyphColumn
    }

!includesub lexi_classes_structure.puml!RELATIONS

'-------------------------------------
' Formatting

package lexi.strategy {
    rectangle GlyphStrategyCompositor
    rectangle GlyphStrategyArrayCompositor
    rectangle GlyphStrategyTeXCompositor
    rectangle GlyphStrategySimpleCompositor
    }

!includesub lexi_classes_format.puml!RELATIONS

'-------------------------------------------
' User interface imbellishment

package lexi.decorator {
    rectangle GlyphDecorator
    rectangle GlyphDecoratorBorder
    rectangle GlyphDecoratorScroller
    }

!includesub lexi_classes_imbellishment.puml!RELATIONS


@enduml