@startuml

title Lexi: Formatting

allowmixing
left to right direction

package lexi.glyph {
    rectangle Glyph
    rectangle GlyphComposite
    }
    
!startsub CLASSES

package lexi.strategy {
    class GlyphStrategyCompositor
    class GlyphStrategyArrayCompositor
    class GlyphStrategyTeXCompositor
    class GlyphStrategySimpleCompositor
    }

!endsub
'-------------------------------------

!startsub MEMBERS

GlyphStrategyCompositor : -composition : GlyphComposite
GlyphStrategyCompositor : +compose()
GlyphStrategyCompositor : +setComposition()

GlyphStrategyArrayCompositor : +compose()
GlyphStrategyTeXCompositor : +compose()
GlyphStrategySimpleCompositor : +compose()

!endsub
'-------------------------------------

!startsub RELATIONS

GlyphStrategyCompositor <|-- GlyphStrategyArrayCompositor
GlyphStrategyCompositor <|-- GlyphStrategyTeXCompositor
GlyphStrategyCompositor <|-- GlyphStrategySimpleCompositor

Glyph <--o "children" GlyphComposite
GlyphComposite "compsitor" o--> GlyphStrategyCompositor
GlyphComposite <-- "composition" GlyphStrategyCompositor

!endsub
'-------------------------------------

!startsub NOTES

note as nGlyphStrategyCompositionInsert
    Glyph::Insert(g, i)
    compositor.compose()
end note 
nGlyphStrategyCompositionInsert .. GlyphComposite::insert

!endsub 



@enduml
