@startuml

skinparam linetype ortho

title Class Adapter Pattern Drawing Editor Example

abstract class Shape
class TextShapeClass
class TextView

Shape : +boundingBox(Point, Point) : void
Shape : +createManipulator() : Manipulator

TextShapeClass : +boundingBox(Point, Point) : void
TextShapeClass : +createManipulator() : Manipulator
TextShapeClass : +isEmpty() : bool

TextView : +getOrigin(Coord,Coord) : void
TextView : +getExtent(Coord,Coord) : void
TextView : +isEmpty() : bool

Shape <|-- TextShapeClass
TextView <|-- TextShapeClass


@enduml
