@startuml

allowmixing
skinparam linetype ortho

title Class Adapter Pattern Formal Structure 

rectangle Client

class Target
class Adaptee
class Adapter


Target : Request()
Adaptee : SpecificRequest()
Adapter : Request()

Target <|-- Adapter
Adaptee <|-- Adapter : implementation

Client --> Target

note as nAdapterSpecificRequest
    SpecificRequest();
end note
nAdapterSpecificRequest . Adapter::SpecificRequest

@enduml
