@startmindmap

title OCCU Computer Sience Courses
*[#lightyellow] OSSU Courses

**[#lightyellow] Core CS
***[#lightyellow] Core Programming

****[#lightyellow] Systematic Program Design
*****[#lightgreen] Simple Data
*****[#lightyellow] Complex Data

****[#lightgreen] Programming Languages (coursera)
*****[#lightgreen] Part A
*****[#lightgreen] Part B
*****[#lightgreen] Part C

****[#lightgreen] Object Oriented Design
*****_ Alberta University Course
*****_ Practical Object Oriented Design Book

****[#lightyellow] Design Patterns
*****_ Design Patterns, \nElements of Reusable Object-Oriented Software
*****_ Domain Driven Design
*****_ Patterns of Enterprise Application Architecture

**** Software Architecture

***[#lightyellow] Core Math

****[#lightyellow] Calculus
*****[#lightyellow] 1A: Differentiation
***** 1B: Integration
***** 1C: Coordinate Systems & Infinit Series
**** Mathematics for Computer Science

*** Core Tools
**** The Missing Symester

*** Core Systems
**** Build a Modern Computer from First Principles:\nNand to Tetris
***** Part I
***** Part II

**** Operating Systems: Three Easy Pieces
**** Computer Networking: a Top-Down Approuch

*** Core Theory

**** **Algorithms and Data Structures**\nDivide and Conquer, Sorting and \nSearching, and Randomized Algorithms
**** **Algorithms and Data Structures**\nGraph Search, Shortest Paths, and Data Structures
**** **Algorithms and Data Structures**\nGreedy Algorithms, Minimum Spanning Trees, \nand Dynamic Programming
**** **Algorithms and Data Structures**\nShortest Paths Revisited, NP-Complete Problems \nand What To Do About Them

*** Core Security

**** Cybersecurity Fundamentals
**** Principles of Secure Coding
**** Identifying Security Vulnerabilities

*** Core Applications

**** Databases: Modeling and Theory
**** Databases: Relational Databases and SQL
**** Databases: Semistructured Data
**** Machine Learning
**** Computer Graphics
**** Software Engineering: Introduction

** Advance CS

@endmindmap
